apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-accounts-deployment
  labels:
    app: bank-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-accounts
  template:
    metadata:
      labels:
        app: bank-accounts
    spec:
      containers:
      - name: bank-accounts
        image: dockerxya/bank-accounts:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: bank-configmap
              key: ACCOUNTS_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: bank-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: bank-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: bank-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: bank-accounts
spec:
  selector:
    app: bank-accounts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
