apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-cards-deployment
  labels:
    app: bank-cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-cards
  template:
    metadata:
      labels:
        app: bank-cards
    spec:
      containers:
      - name: bank-cards
        image: dockerxya/bank-cards:latest
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: bank-configmap
              key: CARDS_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: bank-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: bank-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: bank-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: bank-cards
spec:
  selector:
    app: bank-cards
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
